# Generated by Django 5.1.5 on 2025-01-30 03:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estadisticas', '0003_initial'),
        ('util', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='mesero',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='factura', to='util.mesero'),
        ),
        migrations.AddField(
            model_name='reporte',
            name='grafico',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reporte', to='estadisticas.grafico'),
        ),
    ]
