# Generated by Django 5.1.5 on 2025-01-30 03:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('numero', models.AutoField(primary_key=True, serialize=False)),
                ('total', models.FloatField(default=0.0)),
                ('subtotal', models.FloatField(default=0.0)),
                ('impuesto_total', models.FloatField(default=0.0)),
                ('descuento', models.FloatField(default=0.0)),
                ('fecha', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='HistorialDeFactura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ItemFactura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('subtotal', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='PagoEfectivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_pagado', models.FloatField()),
                ('cuenta_por_cobrar', models.FloatField()),
                ('cambio', models.FloatField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PagoTarjeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_pagado', models.FloatField()),
                ('cuenta_por_cobrar', models.FloatField()),
                ('numero_tarjeta', models.CharField(max_length=16)),
                ('titular', models.CharField(max_length=255)),
                ('vencimiento', models.DateField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PagoTransferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_pagado', models.FloatField()),
                ('cuenta_por_cobrar', models.FloatField()),
                ('numero_transferencia', models.CharField(max_length=50)),
                ('banco_origen', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Promocion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255)),
                ('porcentaje_descuento', models.FloatField()),
            ],
        ),
    ]
