# Generated by Django 5.1.5 on 2025-01-30 23:14

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pedidos', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='PagoEfectivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_pagado', models.FloatField()),
                ('cuenta_por_cobrar', models.FloatField()),
                ('cambio', models.FloatField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PagoTarjeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_pagado', models.FloatField()),
                ('cuenta_por_cobrar', models.FloatField()),
                ('numero_tarjeta', models.CharField(max_length=16)),
                ('titular', models.CharField(max_length=255)),
                ('vencimiento', models.DateField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PagoTransferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_pagado', models.FloatField()),
                ('cuenta_por_cobrar', models.FloatField()),
                ('numero_transferencia', models.CharField(max_length=50)),
                ('banco_origen', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Promocion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255)),
                ('porcentaje_descuento', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('numero', models.AutoField(primary_key=True, serialize=False)),
                ('total', models.FloatField(default=0.0)),
                ('subtotal', models.FloatField(default=0.0)),
                ('impuesto_total', models.FloatField(default=0.0)),
                ('descuento', models.FloatField(default=0.0)),
                ('fecha', models.DateField(default=datetime.date.today)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedidos.pedido')),
                ('metodo_pago_efectivo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='facturacion.pagoefectivo')),
                ('metodo_pago_tarjeta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='facturacion.pagotarjeta')),
                ('metodo_pago_transferencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='facturacion.pagotransferencia')),
                ('promocion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='facturacion.promocion')),
            ],
        ),
        migrations.CreateModel(
            name='HistorialDeFactura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facturacion.factura')),
            ],
        ),
        migrations.CreateModel(
            name='ItemFactura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('subtotal', models.FloatField()),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='facturacion.factura')),
                ('item_pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedidos.itempedido')),
            ],
        ),
    ]
