# Generated by Django 5.1.5 on 2025-01-31 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocion',
            name='activa',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='promocion',
            name='tipo_clima',
            field=models.CharField(default='Desconocido', help_text='Ej: Lluvia, Soleado, Nublado', max_length=50),
        ),
    ]
