# Generated by Django 5.1.5 on 2025-01-30 03:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('facturacion', '0001_initial'),
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedidos.pedido'),
        ),
        migrations.AddField(
            model_name='historialdefactura',
            name='factura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facturacion.factura'),
        ),
        migrations.AddField(
            model_name='itemfactura',
            name='factura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='facturacion.factura'),
        ),
        migrations.AddField(
            model_name='itemfactura',
            name='item_pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedidos.itempedido'),
        ),
        migrations.AddField(
            model_name='factura',
            name='metodo_pago_efectivo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='facturacion.pagoefectivo'),
        ),
        migrations.AddField(
            model_name='factura',
            name='metodo_pago_tarjeta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='facturacion.pagotarjeta'),
        ),
        migrations.AddField(
            model_name='factura',
            name='metodo_pago_transferencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='facturacion.pagotransferencia'),
        ),
        migrations.AddField(
            model_name='factura',
            name='promocion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='facturacion.promocion'),
        ),
    ]
