# Generated by Django 5.1.5 on 2025-02-02 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocion',
            name='porcentaje_descuento',
            field=models.FloatField(help_text='Ej: 10 para 10%'),
        ),
    ]
