# Generated by Django 5.1.5 on 2025-02-02 00:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0003_alter_promocion_porcentaje_descuento'),
        ('menus', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factura',
            name='promocion',
        ),
        migrations.AddField(
            model_name='factura',
            name='promociones',
            field=models.ManyToManyField(blank=True, to='facturacion.promocion'),
        ),
        migrations.AddField(
            model_name='promocion',
            name='producto',
            field=models.ForeignKey(blank=True, help_text='Dejar en blanco si aplica a toda la factura', null=True, on_delete=django.db.models.deletion.CASCADE, to='menus.producto'),
        ),
        migrations.AlterField(
            model_name='promocion',
            name='porcentaje_descuento',
            field=models.FloatField(),
        ),
    ]
