# Generated by Django 5.1.5 on 2025-02-02 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0004_remove_factura_promocion_factura_promociones_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemfactura',
            name='cantidad',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='itemfactura',
            name='subtotal',
            field=models.FloatField(editable=False),
        ),
    ]
