# Generated by Django 5.1.5 on 2025-02-01 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador', models.CharField(max_length=50, unique=True)),
                ('numero_asientos', models.PositiveIntegerField()),
                ('ubicacion', models.CharField(max_length=100)),
                ('estado', models.CharField(choices=[('LIBRE', 'Libre'), ('OCUPADA', 'Ocupada'), ('RESERVADA', 'Reservada')], default='LIBRE', max_length=10)),
                ('hora_disponible', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador', models.CharField(max_length=50, unique=True)),
                ('cantidad_personas', models.PositiveIntegerField()),
                ('fecha_reserva', models.DateField()),
                ('horario_inicio', models.DateTimeField()),
                ('hora_reserva_finalizada', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('CONFIRMADA', 'Confirmada'), ('CANCELADA', 'Cancelada'), ('FINALIZADA', 'Finalizada'), ('EN_CURSO', 'En Curso')], default='CONFIRMADA', max_length=15)),
            ],
        ),
    ]
