# Generated by Django 5.1.5 on 2025-01-30 23:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('util', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador', models.CharField(max_length=50)),
                ('numero_asientos', models.IntegerField()),
                ('ubicacion', models.CharField(max_length=100)),
                ('estado', models.CharField(choices=[('LIBRE', 'LIBRE'), ('OCUPADA', 'OCUPADA'), ('RESERVADA', 'RESERVADA')], default='LIBRE', max_length=10, verbose_name='Estado')),
                ('hora_disponible', models.DateTimeField(blank=True, null=True)),
                ('mesas_unidas', models.ManyToManyField(blank=True, to='mesas.mesa')),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador', models.CharField(max_length=50)),
                ('cantidad_personas', models.IntegerField()),
                ('fecha_reserva', models.DateField()),
                ('horario_inicio', models.DateTimeField()),
                ('hora_reserva_finalizada', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('CONFIRMADA', 'CONFIRMADA'), ('CANCELADA', 'CANCELADA'), ('FINALIZADA', 'FINALIZADA'), ('ENCURSO', 'ENCURSO')], default='CONFIRMADA', max_length=15)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='util.cliente')),
                ('mesa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mesas.mesa')),
            ],
        ),
    ]
