# Generated by Django 5.1.5 on 2025-01-30 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=10, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=50)),
                ('edad', models.IntegerField(blank=True, null=True)),
                ('telefono', models.CharField(max_length=15, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('identificacion', models.CharField(editable=False, max_length=7, null=True, unique=True)),
                ('rol', models.CharField(choices=[('MESERO', 'MESERO'), ('SECRETARIO', 'SECRETARIO'), ('ADMINISTRADOR', 'ADMINISTRADOR'), ('COCINERO', 'COCINERO')], default='MESERO', max_length=15)),
                ('revision', models.TextField()),
                ('control', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Impuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('porcentaje', models.FloatField()),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mesero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=10, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=50)),
                ('edad', models.IntegerField(blank=True, null=True)),
                ('telefono', models.CharField(max_length=15, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('identificacion', models.CharField(editable=False, max_length=7, null=True, unique=True)),
                ('rol', models.CharField(choices=[('MESERO', 'MESERO'), ('SECRETARIO', 'SECRETARIO'), ('ADMINISTRADOR', 'ADMINISTRADOR'), ('COCINERO', 'COCINERO')], default='MESERO', max_length=15)),
                ('esta_ocupado', models.BooleanField(default=False, editable=False)),
                ('pedidos_atendidos', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PersonalCocina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=10, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=50)),
                ('edad', models.IntegerField(blank=True, null=True)),
                ('telefono', models.CharField(max_length=15, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('identificacion', models.CharField(editable=False, max_length=7, null=True, unique=True)),
                ('rol', models.CharField(choices=[('MESERO', 'MESERO'), ('SECRETARIO', 'SECRETARIO'), ('ADMINISTRADOR', 'ADMINISTRADOR'), ('COCINERO', 'COCINERO')], default='MESERO', max_length=15)),
                ('esta_cocinando', models.BooleanField(default=False, editable=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('direccion', models.CharField(max_length=255)),
                ('contacto', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('rol', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=10, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=50)),
                ('edad', models.IntegerField(blank=True, null=True)),
                ('telefono', models.CharField(max_length=15, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('historial_pedidos', models.ManyToManyField(blank=True, related_name='clientes_historial', to='pedidos.pedido')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
