# Generated by Django 5.1.5 on 2025-02-02 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0004_pedido_mesero'),
        ('util', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mesero',
            name='pedidos',
            field=models.ManyToManyField(blank=True, related_name='mesero_pedidos', to='pedidos.pedido'),
        ),
    ]
