# Generated by Django 5.1.5 on 2025-02-02 00:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registrohistorico',
            options={},
        ),
        migrations.AddField(
            model_name='registrohistorico',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 2, 1, 0, 0)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='registrohistorico',
            name='pedidos',
            field=models.ManyToManyField(blank=True, to='pedidos.pedido'),
        ),
    ]
