# Generated by Django 5.1.5 on 2025-02-02 01:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0004_pedido_mesero'),
        ('util', '0002_mesero_pedidos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='mesero',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_mesero', to='util.mesero'),
        ),
    ]
