# Generated by Django 5.1.5 on 2025-02-02 01:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mesas', '0002_initial'),
        ('pedidos', '0005_alter_pedido_mesero'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='mesa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_mesa', to='mesas.mesa'),
        ),
    ]
