# Generated by Django 5.1.5 on 2025-02-02 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0006_pedido_mesa'),
    ]

    operations = [
        migrations.AddField(
            model_name='itempedido',
            name='pokemon_regalo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
