# Generated by Django 5.1.5 on 2025-02-02 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0007_itempedido_pokemon_regalo'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='pokemon',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
