# Generated by Django 5.1.5 on 2025-02-02 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0008_pedido_pokemon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itempedido',
            old_name='pokemon_regalo',
            new_name='pokemon_nombre',
        ),
        migrations.AddField(
            model_name='itempedido',
            name='pokemon_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
