# Generated by Django 5.1.5 on 2025-02-02 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0009_rename_pokemon_regalo_itempedido_pokemon_nombre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itempedido',
            name='pokemon_regalo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
