# Generated by Django 5.1.5 on 2025-02-02 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0010_itempedido_pokemon_regalo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itempedido',
            name='pokemon_regalo',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='pokemon',
        ),
        migrations.AlterField(
            model_name='itempedido',
            name='pokemon_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
